

analyseAbsorption:
	g++ analyseAbsorption.cpp -I `root-config --incdir` `root-config --libs` -o analyseAbsorption

averagePixelResults:
	g++ averagePixelResults.cpp -I `root-config --incdir` `root-config --libs` -o averagePixelResults

absorptionPixelSum:
	g++ absorptionPixelSum.cpp -I `root-config --incdir` `root-config --libs` -o absorptionPixelSum

clean:
	rm analyseAbsorption averagePixelResults absorptionPixelSum
